### ISSUE TITLE
Endpoint /sessionextend does not extend the session

### ISSUE THREAD

**Issue by GravelCZ** [mariansam/bakalari-disable-timeout#1]
~~Some of the new versions of bakalaři do not reset the session timer, you can check this by going to the endpoint /sessioninfo that returns the remaining time of your session~~
The endpoint /sessionextend does not give the new sessioncookie unless the timer is less then the time given in the code. for the that is <=((sessionduration / 5) * 60) = 3 minues. the sessionduration is requested from endpoint /sessioninfo or defaults to 15

**Comment by GravelCZ** [comment]
Or there is a prevention that blocks you from making the request manually

**Comment by mariansam** [comment]
Thanks! I didn't notice that, because I'm not using Bakaláři that much these days. I'll take a look at it.

**Comment by mariansam** [comment]
It works on my machine™. When I go to `/sessioninfo` the `remainingTime` property displays the seconds remaining to the end of the session. When it's ~~<300~~ (edit: <600 i think), the `/sessionextend` endpoint extends it back to 900.

The script requests `/sessionextend` every 30 seconds and since 30 is less than 300, it should work every time. Make sure your computer is connected to the Internet, otherwise it can't work – I'll add a warning to the readme (edit: done, 698c86d76e2f4c4f7dd1d518c3562c778f0b2afb).

One weird thing is that in the Developer tools in the Console I see the message `Fetch failed loading: GET "https://bakalari.xxx.cz/sessionextend".`, but in the Network tab I see the request completed with the status 200 OK. I don't know what's happening there. I'll add an error handler just to be sure if something goes wrong (edit: done, ae96007cfd9f388074e695f6a86e6e004ebf0c5e).

**Comment by GravelCZ** [comment]
It seems that Greasemonkey for Firefox does not call the setTimeout function but the message "bakalari-disable-timeout: started" gets printed to console. The code works fine when put into the console manually, including the type check for appRoot.

**Comment by mariansam** [comment]
Greasemonkey isolates the userscript, so the `appRoot` variable isn't accessible and the `fetch` function requires the domain. Fixed in f43b5e371c7fd6c0936b743107eef1e9e8ee788a. Thanks for the feedback. Let me know it it works.

**Comment by GravelCZ** [comment]
It seems to be working just fine now, thank you so much!
